// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_SET_screen_init(void)
{
    ui_SET = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SET, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SET,lv_color_hex(0x778899), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SET,255,LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_SET);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 1);
    lv_obj_set_y(ui_Label4, -105);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "SET");

     /*Create a list*/
    list1 = lv_list_create(ui_SET);
    // lv_obj_set_size(list1, 180, 220);
    // lv_obj_center(list1);
    lv_obj_set_width(list1, 247);   /// 1
    lv_obj_set_height(list1, 180);    /// 1
    lv_obj_set_x(list1, 1);
    lv_obj_set_y(list1, 3);
    lv_obj_set_align(list1, LV_ALIGN_CENTER);

    /*将按钮添加到列表*/
    lv_obj_t * btn;

    lv_list_add_text(list1, "Connectivity");
    btn = lv_list_add_btn(list1, LV_SYMBOL_WIFI, "Wi-Fi");
    btn = lv_list_add_btn(list1, LV_SYMBOL_BLUETOOTH, "Bluetooth");
    btn = lv_list_add_btn(list1, LV_SYMBOL_GPS, "Navigation");
    btn = lv_list_add_btn(list1, LV_SYMBOL_USB, "USB");
    btn = lv_list_add_btn(list1, LV_SYMBOL_BATTERY_FULL, "Battery");
    
    lv_list_add_text(list1, "File");
    btn = lv_list_add_btn(list1, LV_SYMBOL_FILE, "New");
    btn = lv_list_add_btn(list1, LV_SYMBOL_DIRECTORY, "Open");
    btn = lv_list_add_btn(list1, LV_SYMBOL_SAVE, "Save");
    btn = lv_list_add_btn(list1, LV_SYMBOL_CLOSE, "Delete");
    btn = lv_list_add_btn(list1, LV_SYMBOL_EDIT, "Edit");

    

    lv_obj_add_event_cb(ui_SET, ui_event_SET, LV_EVENT_ALL, NULL);

}
