// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: 1

#include "../ui.h"



void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x4682B4), LV_PART_MAIN);

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 111);
    lv_obj_set_height(ui_Panel1, 50);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, -47);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xDCDCDC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hour = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_hour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hour, -25);
    lv_obj_set_y(ui_hour, 1);
    lv_obj_set_align(ui_hour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hour, "09");
    lv_obj_set_style_text_color(ui_hour, lv_color_hex(0xDAA520), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_hour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_hour, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minute = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_minute, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_minute, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_minute, 9);
    lv_obj_set_y(ui_minute, 1);
    lv_obj_set_align(ui_minute, LV_ALIGN_CENTER);
    lv_label_set_text(ui_minute, "28");
    lv_obj_set_style_text_color(ui_minute, lv_color_hex(0xDAA520), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_minute, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_minute, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_second = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_second, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_second, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_second, 34);
    lv_obj_set_y(ui_second, 6);
    lv_obj_set_align(ui_second, LV_ALIGN_CENTER);
    lv_label_set_text(ui_second, "00");
    lv_obj_set_style_text_color(ui_second, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_second, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -8);
    lv_obj_set_y(ui_Label6, 0);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, ":");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xDAA520), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_YearMonDa = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_YearMonDa, 60);
    lv_obj_set_height(ui_YearMonDa, 10);
    lv_obj_set_x(ui_YearMonDa, 0);
    lv_obj_set_y(ui_YearMonDa, -16);
    lv_obj_set_align(ui_YearMonDa, LV_ALIGN_CENTER);
    lv_label_set_text(ui_YearMonDa, "1990/01/01");
    lv_obj_set_style_text_font(ui_YearMonDa, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_week = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_week, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_week, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_week, 0);
    lv_obj_set_y(ui_week, 17);
    lv_obj_set_align(ui_week, LV_ALIGN_CENTER);
    lv_label_set_text(ui_week, "Monday");
    lv_obj_set_style_text_font(ui_week, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setup = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_setup, 24);
    lv_obj_set_height(ui_setup, 24);
    lv_obj_set_x(ui_setup, 48);
    lv_obj_set_y(ui_setup, 65);
    lv_obj_set_align(ui_setup, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_setup, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_setup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_setup, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_setup, &ui_img_1305147399, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menu = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_menu, 24);
    lv_obj_set_height(ui_menu, 24);
    lv_obj_set_x(ui_menu, -48);
    lv_obj_set_y(ui_menu, 66);
    lv_obj_set_align(ui_menu, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_menu, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_menu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_menu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_menu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_menu, &ui_img_menu24x24_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 96);
    lv_obj_set_height(ui_Container1, 44);
    lv_obj_set_x(ui_Container1, 1);
    lv_obj_set_y(ui_Container1, 11);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_Container1);
    lv_img_set_src(ui_Image1, &ui_img_99_png);
    lv_obj_set_width(ui_Image1, 24);
    lv_obj_set_height(ui_Image1, 24);
    lv_obj_set_x(ui_Image1, 17);
    lv_obj_set_y(ui_Image1, -12);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Temp = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temp, -24);
    lv_obj_set_y(ui_Temp, -12);
    lv_obj_set_align(ui_Temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temp, "0°");
    lv_obj_set_style_text_font(ui_Temp, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MaxMinWea = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_MaxMinWea, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MaxMinWea, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MaxMinWea, 0);
    lv_obj_set_y(ui_MaxMinWea, 10);
    lv_obj_set_align(ui_MaxMinWea, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MaxMinWea, "Max0° Min0°");
    lv_obj_set_style_text_font(ui_MaxMinWea, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image2, &ui_img_disconnect_png);
    lv_obj_set_width(ui_Image2, 24);
    lv_obj_set_height(ui_Image2, 24);
    lv_obj_set_x(ui_Image2, 0);
    lv_obj_set_y(ui_Image2, 65);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_screen_event_add();
}


