// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: 1

#ifndef _1_UI_H
#define _1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif


#include "ui_helpers.h"
#include "ui_events.h"
#include "event.h"
extern void ui_screen_event_add(void);
extern void lv_Screen2_Init(void);

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_hour;
extern lv_obj_t * ui_minute;
extern lv_obj_t * ui_second;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_YearMonDa;
extern lv_obj_t * ui_week;
extern lv_obj_t * ui_setup;
extern lv_obj_t * ui_menu;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Temp;
extern lv_obj_t * ui_MaxMinWea;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_1305147399);    // assets/set-up24x24.png
LV_IMG_DECLARE(ui_img_menu24x24_png);    // assets/menu24x24.png
LV_IMG_DECLARE(ui_img_99_png);    // assets/99.png
LV_IMG_DECLARE(ui_img_connect_png);    // assets/connect.png
LV_IMG_DECLARE(ui_img_disconnect_png);    // assets/disconnect_png.png
LV_IMG_DECLARE(ui_img_0_png);    // assets/0.png
LV_IMG_DECLARE(ui_img_1_png);    // assets/1.png
LV_IMG_DECLARE(ui_img_10_png);    // assets/10.png
LV_IMG_DECLARE(ui_img_11_png);    // assets/11.png
LV_IMG_DECLARE(ui_img_12_png);    // assets/12.png
LV_IMG_DECLARE(ui_img_13_png);    // assets/13.png
LV_IMG_DECLARE(ui_img_14_png);    // assets/14.png
LV_IMG_DECLARE(ui_img_15_png);    // assets/15.png
LV_IMG_DECLARE(ui_img_16_png);    // assets/16.png
LV_IMG_DECLARE(ui_img_17_png);    // assets/17.png
LV_IMG_DECLARE(ui_img_18_png);    // assets/18.png
LV_IMG_DECLARE(ui_img_19_png);    // assets/19.png
LV_IMG_DECLARE(ui_img_2_png);    // assets/2.png
LV_IMG_DECLARE(ui_img_20_png);    // assets/20.png
LV_IMG_DECLARE(ui_img_21_png);    // assets/21.png
LV_IMG_DECLARE(ui_img_22_png);    // assets/22.png
LV_IMG_DECLARE(ui_img_23_png);    // assets/23.png
LV_IMG_DECLARE(ui_img_24_png);    // assets/24.png
LV_IMG_DECLARE(ui_img_25_png);    // assets/25.png
LV_IMG_DECLARE(ui_img_26_png);    // assets/26.png
LV_IMG_DECLARE(ui_img_27_png);    // assets/27.png
LV_IMG_DECLARE(ui_img_28_png);    // assets/28.png
LV_IMG_DECLARE(ui_img_29_png);    // assets/29.png
LV_IMG_DECLARE(ui_img_3_png);    // assets/3.png
LV_IMG_DECLARE(ui_img_30_png);    // assets/30.png
LV_IMG_DECLARE(ui_img_31_png);    // assets/31.png
LV_IMG_DECLARE(ui_img_32_png);    // assets/32.png
LV_IMG_DECLARE(ui_img_33_png);    // assets/33.png
LV_IMG_DECLARE(ui_img_34_png);    // assets/34.png
LV_IMG_DECLARE(ui_img_35_png);    // assets/35.png
LV_IMG_DECLARE(ui_img_36_png);    // assets/36.png
LV_IMG_DECLARE(ui_img_37_png);    // assets/37.png
LV_IMG_DECLARE(ui_img_38_png);    // assets/38.png
LV_IMG_DECLARE(ui_img_4_png);    // assets/4.png
LV_IMG_DECLARE(ui_img_5_png);    // assets/5.png
LV_IMG_DECLARE(ui_img_6_png);    // assets/6.png
LV_IMG_DECLARE(ui_img_7_png);    // assets/7.png
LV_IMG_DECLARE(ui_img_8_png);    // assets/8.png
LV_IMG_DECLARE(ui_img_9_png);    // assets/9.png

LV_IMG_DECLARE(ui_img_exit_png);    // assets/Exit.png
LV_IMG_DECLARE(ui_img_w_c_png);    // assets/w_c.png
LV_IMG_DECLARE(ui_img_w_c_f_png);    // assets/w_c_f.png
LV_IMG_DECLARE(ui_img_w_c_s_png);    // assets/w_c_s.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
