// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: 1

#ifndef _1_UI_H
#define _1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_hour;
extern lv_obj_t * ui_minute;
extern lv_obj_t * ui_second;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_YearMonDa;
extern lv_obj_t * ui_week;
extern lv_obj_t * ui_setup;
extern lv_obj_t * ui_menu;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_1305147399);    // assets/set-up24x24.png
LV_IMG_DECLARE(ui_img_menu24x24_png);    // assets/menu24x24.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
