// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Control_interface_screen_init(void)
{
    ui_Control_interface = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Control_interface, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Control_interface, lv_color_hex(0x778899), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Control_interface, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Control_interface);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, -93);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "AI");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea1 = lv_textarea_create(ui_Control_interface);
    lv_obj_set_width(ui_TextArea1, 307);
    lv_obj_set_height(ui_TextArea1, 48);
    lv_obj_set_x(ui_TextArea1, 3);
    lv_obj_set_y(ui_TextArea1, -48);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea1, "me sak...");
    lv_obj_set_style_text_font(ui_TextArea1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_TextArea2 = lv_textarea_create(ui_Control_interface);
    lv_obj_set_width(ui_TextArea2, 309);
    lv_obj_set_height(ui_TextArea2, 110);
    lv_obj_set_x(ui_TextArea2, 3);
    lv_obj_set_y(ui_TextArea2, 31);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea2, "”");
    lv_textarea_set_placeholder_text(ui_TextArea2, "AI answer...");
    lv_obj_set_style_text_font(ui_TextArea2, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Button1 = lv_btn_create(ui_Control_interface);
    lv_obj_set_width(ui_Button1, 63);
    lv_obj_set_height(ui_Button1, 28);
    lv_obj_set_x(ui_Button1, 2);
    lv_obj_set_y(ui_Button1, 104);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xB0E0E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Send");

    ui_Keyboard1 = lv_keyboard_create(ui_Control_interface);
    lv_obj_set_width(ui_Keyboard1, 300);
    lv_obj_set_height(ui_Keyboard1, 120);
    lv_obj_set_x(ui_Keyboard1, -1);
    lv_obj_set_y(ui_Keyboard1, 41);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_set_scrollbar_mode(ui_Keyboard1, LV_SCROLLBAR_MODE_ON);

    lv_obj_add_event_cb(ui_TextArea1, ui_event_TextArea1, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_TextArea1);
    lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);
}
