// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: 1

#ifndef _1_UI_H
#define _1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_wifilabel;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Dropdown1;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_exit_png);    // assets/Exit.png
LV_IMG_DECLARE(ui_img_w_c_png);    // assets/w_c.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
