// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Image3;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;


// SCREEN: ui_MENU
void ui_MENU_screen_init(void);
lv_obj_t * ui_MENU;
lv_obj_t * ui_Label3;
void ui_event_Label5(lv_event_t * e);
lv_obj_t * ui_Label5;
void ui_event_Label7(lv_event_t * e);
lv_obj_t * ui_Label7;


// SCREEN: ui_SET
void ui_SET_screen_init(void);
void ui_event_SET(lv_event_t * e);
lv_obj_t * ui_SET;
lv_obj_t * ui_Label4;


// SCREEN: ui_Control_interface
void ui_Control_interface_screen_init(void);
lv_obj_t * ui_Control_interface;
lv_obj_t * ui_Label6;
void ui_event_TextArea1(lv_event_t * e);
lv_obj_t * ui_TextArea1;
lv_obj_t * ui_TextArea2;
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label8;
void ui_event_Keyboard1(lv_event_t * e);
lv_obj_t * ui_Keyboard1;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_[40] = {&ui_img_0_png, &ui_img_1_png, &ui_img_10_png, &ui_img_11_png, &ui_img_12_png, &ui_img_2_png, &ui_img_13_png, &ui_img_3_png, &ui_img_14_png, &ui_img_4_png, &ui_img_15_png, &ui_img_5_png, &ui_img_16_png, &ui_img_6_png, &ui_img_17_png, &ui_img_7_png, &ui_img_18_png, &ui_img_8_png, &ui_img_19_png, &ui_img_20_png, &ui_img_21_png, &ui_img_22_png, &ui_img_23_png, &ui_img_24_png, &ui_img_25_png, &ui_img_26_png, &ui_img_27_png, &ui_img_28_png, &ui_img_29_png, &ui_img_30_png, &ui_img_31_png, &ui_img_32_png, &ui_img_33_png, &ui_img_34_png, &ui_img_35_png, &ui_img_36_png, &ui_img_37_png, &ui_img_38_png, &ui_img_9_png, &ui_img_99_png};
const lv_img_dsc_t * ui_imgset_menux[1] = {&ui_img_menu24x24_png};
const lv_img_dsc_t * ui_imgset_1973940768[1] = {&ui_img_1305147399};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SET, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SET_screen_init);
    }
}
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MENU, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MENU_screen_init);
    }
}
void ui_event_Label5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Control_interface, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Control_interface_screen_init);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_Label7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Control_interface, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Control_interface_screen_init);
        _ui_checked_set_text_value(ui_Label6, target, "Language chat", "Language chat");
    }
}
void ui_event_SET(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_TextArea1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard1,  ui_TextArea1);
    }
}
void ui_event_Keyboard1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_MENU_screen_init();
    ui_SET_screen_init();
    ui_Control_interface_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
